name: Shared functionality for the Build & Deploy workflows

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
    secrets:
      azure_password:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code onto job runner
      uses: actions/checkout@v2
      
    - name: Install Node.JS (v14)
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install .Net (6.0)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Save the build number to build-number.json
      run: |
        echo '{ BuildNumber: ${{ github.run_number }} }' > build-number.json
      working-directory: ./HerPublicWebsite

    - name: Restore Node.JS dependencies
      run: npm ci
      working-directory: ./HerPublicWebsite
      
    - name: Build SCSS and JS code
      run: npm run build
      working-directory: ./HerPublicWebsite
      
    - name: Restore .Net dependencies
      run: dotnet restore --configfile nuget.config
      
    - name: Build .Net code
      run: dotnet build HerPublicWebsite --no-restore --configuration Release --output ./ci-server-build/

    - name: Push the app to Azure
      # TODO fill this in for Azure environment
      working-directory: ./ci-server-build/
